### ISSUE TITLE
Electrum Server fails to start when trying to run Docker Toolbox on Windows

### ISSUE THREAD

**Issue by TheCharlatan** [lukechilds/docker-electrumx#11]
I'm trying to setup the ElectrumX server on windows, but receive the following errors currently:

```
docker run --net=host -v ~/electrumx:/data -e DAEMON_URL="rpcuser:123456@127.0.0.1:8332" -e COIN=BitcoinSegwit -e NET=testnet -e RPC_HOST=127.0.0.1 -e RPC_PORT=8332 -p 5
0002:50002 lukechilds/electrumx
WARNING: Published ports are discarded when using host network mode
INFO:root:ElectrumX server starting
INFO:Controller:event loop policy: None
INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
INFO:BlockProcessor:switching current directory to /data
INFO:BlockProcessor:using leveldb for DB backend
Traceback (most recent call last):
  File "/electrumx/electrumx_server.py", line 25, in main
    controller = Controller(Env())
  File "/electrumx/server/controller.py", line 84, in __init__
    self.bp = self.coin.BLOCK_PROCESSOR(env, self, self.daemon)
  File "/electrumx/server/block_processor.py", line 145, in __init__
    super().__init__(env)
  File "/electrumx/server/db.py", line 68, in __init__
    self.open_dbs()
  File "/electrumx/server/db.py", line 116, in open_dbs
    self.utxo_db = self.db_class('utxo', for_sync)
  File "/electrumx/server/storage.py", line 31, in __init__
    self.open(name, create=self.is_new)
  File "/electrumx/server/storage.py", line 83, in open
    max_open_files=mof)
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: b'IO error: utxo: Invalid argument'
CRITICAL:root:ElectrumX server terminated abnormally
```

Any hints on what might cause this?

**Comment by lukechilds** [comment]
Not sure if it's related but can you do `~/electrumx` on Windows?

**Comment by lukechilds** [comment]
Closing due to inactivity and that it seems to be caused by external software.

Feel free to re-open the issue if you find it is indeed an issue with this Dockerfile or you have more information.
